function Dashboard() {

    return (
        <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent leo sem, condimentum non laoreet eu, imperdiet ut lectus. Maecenas sit amet ante non justo rutrum eleifend nec a leo. Curabitur auctor euismod lorem quis tincidunt. Nullam accumsan quis lorem cursus sodales. Curabitur pulvinar pulvinar lobortis. Cras leo metus, aliquet sit amet nibh nec, luctus consequat lacus. Nullam volutpat, ante non luctus mollis, tortor mi venenatis quam, id semper nulla tortor quis purus. Nulla et elementum nibh. Nulla sit amet mi et neque molestie cursus. Mauris quis tempor leo. Nulla sit amet justo a massa rhoncus pharetra. Integer semper convallis nulla non venenatis.
            <br/><br/>
            Sed eleifend, magna sit amet porttitor condimentum, diam enim facilisis leo, facilisis dapibus ipsum eros vitae turpis. Quisque hendrerit non lacus id efficitur. Pellentesque consequat, quam eu ultricies ullamcorper, lacus ipsum porta tortor, eget euismod nunc lorem vel magna. Quisque nibh lacus, iaculis nec ultrices ut, venenatis eget nisi. Quisque orci ipsum, suscipit nec elit sed, efficitur lobortis nibh. Sed hendrerit enim augue, ut elementum urna lobortis vel. Nulla at sodales risus. Morbi bibendum enim non lacus varius, eu mollis mauris ornare. Phasellus vel metus ut ante condimentum finibus in at mauris. In ut vestibulum arcu. Nulla pretium odio imperdiet erat egestas venenatis. Curabitur ac lorem dolor. Curabitur nec nisl tincidunt, ullamcorper justo sit amet, porta turpis. Fusce mollis, eros eu porta dignissim, elit eros volutpat dolor, eu facilisis dui sapien sit amet velit. Cras mi enim, maximus a dolor vitae, pellentesque pellentesque elit. Proin iaculis fringilla metus nec dictum.
            <br/><br/>
            Duis maximus lacus a ullamcorper egestas. Mauris elit erat, venenatis vitae fringilla eu, accumsan non risus. Proin eu varius velit. Aliquam erat volutpat. Etiam ut rhoncus purus, gravida tempor sem. Aenean vel rutrum dui. In ultricies sem at leo malesuada fringilla. Sed eget orci ac est eleifend interdum vel sed justo. Donec gravida mi ut felis consequat, ut maximus elit molestie. Phasellus sodales sapien a venenatis tempus. Nunc porttitor justo at metus molestie porta.
            <br/><br/>
            Suspendisse porta quis mauris vitae efficitur. Mauris non aliquam lectus. Integer in hendrerit tellus. Fusce pharetra ipsum ut neque dignissim pulvinar. Ut a metus vitae nisi fermentum volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla facilisi. Nam efficitur libero sit amet ligula blandit dictum. Etiam ut risus ex. Cras quis purus massa. Suspendisse et tellus vel velit lacinia maximus. Pellentesque in tortor a dolor ultricies faucibus eu a libero. Ut malesuada rutrum lorem, pharetra commodo magna efficitur elementum. Aliquam sollicitudin dui a urna varius, faucibus commodo nulla semper. Aenean a arcu dolor. Vestibulum viverra ipsum eu mauris tristique, semper semper purus auctor.
            <br/><br/>
            Proin posuere viverra ex eget mollis. Phasellus vestibulum faucibus enim, eget scelerisque mi semper vitae. Sed luctus, leo eget dictum convallis, nibh sem cursus lacus, et cursus massa turpis non sem. Duis pellentesque turpis sit amet quam iaculis bibendum. Praesent porttitor ac odio sit amet consectetur. Maecenas at pretium ligula. Etiam sapien eros, fringilla non hendrerit et, sollicitudin non mauris. Mauris fermentum ornare est nec dapibus.
        </div>
    )
}
export default Dashboard;